language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t bohdaninhliziian/docker-react .

script:
  - docker run -e CI=true bohdaninhliziian/docker-react npm run test

deploy:
  provider: elasticbeantalk
  region: "eu-central-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-eu-central-1-438133126510"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
